# Generated by Django 3.2 on 2023-05-10 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('patent', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad de Pasajeros')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('name', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('name', models.CharField(max_length=100, verbose_name='Experiencia')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('name', models.CharField(max_length=100, verbose_name='Caracteristicas')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('name', models.CharField(max_length=100, verbose_name='Modalidad')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('url', models.URLField()),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='TypePost',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de publicacion')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            bases=('publication.basicmodel',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.basicmodel')),
                ('title', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Publicación')),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='imagesPublication/')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('status', models.BooleanField(default=False)),
                ('type_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publication.typepost')),
            ],
            bases=('publication.basicmodel',),
        ),
    ]
